namespace: rridane
name: base_systems
version: 1.0.2

readme: README.md

authors:
  - rridane <rridane@rr-dev.com>

description: >
  System hardening & Kubernetes toolkit for Debian/Ubuntu: proxy, swap, sysctl,
  containerd, HAProxy/Keepalived, kube packages, and admin CLIs (kubectl, helm, k9s, krew).

license:
  - MIT

tags:
  - ansible
  - linux
  - kubernetes
  - containerd
  - haproxy
  - keepalived
  - sysctl
  - proxy
  - krew
  - k9s
  - helm
  - debian
  - ubuntu

dependencies: {}

repository: https://github.com/rridane/ansible-base-systems
documentation: https://github.com/rridane/ansible-base-systems
homepage: https://github.com/rridane/ansible-base-systems
issues: https://github.com/rridane/ansible-base-systems

build_ignore:
  # VCS / IDE / env
  - ".git"
  - ".git/**"
  - ".github"
  - ".github/**"
  - ".gitignore"
  - ".editorconfig"
  - ".pre-commit-config.yaml"
  - ".idea"
  - ".idea/**"
  - ".vscode"
  - ".vscode/**"

  # Environnements virtuels (tous niveaux)
  - ".venv"
  - ".venv/**"
  - "venv"
  - "venv/**"
  - "**/.venv"
  - "**/.venv/**"
  - "**/venv"
  - "**/venv/**"

  # Caches/tests
  - ".tox"
  - ".tox/**"
  - ".mypy_cache"
  - ".mypy_cache/**"
  - "__pycache__"
  - "**/__pycache__/**"
  - ".pytest_cache"
  - ".pytest_cache/**"

  # Artefacts
  - "dist"
  - "dist/**"
  - "*.tar.gz"
  - "*.zip"
  - "*.log"
  - "*.retry"

  # Molecule (si tu ne veux pas les publier)
  - "roles/*/molecule"
  - "roles/*/molecule/**"

  # Docs lourdes
  - "docs"
  - "docs/**"
  - "assets"
  - "assets/**"
  - "images"
  - "images/**"
  - "screenshots"
  - "screenshots/**"

  # Grosse binaires éventuels
  - "roles/*/files/*.tar"
  - "roles/*/files/*.tar.gz"
  - "roles/*/files/*.tgz"
  - "roles/*/files/*.zip"
  - "roles/*/files/*.deb"
  - "roles/*/files/*.rpm"
