namespace: rridane
name: base_systems
version: 0.1.0

readme: README.md

authors:
  - rridane <rridane@rr-dev.com>

description: >
  System hardening & Kubernetes toolkit for Debian/Ubuntu: proxy, swap, sysctl,
  containerd, HAProxy/Keepalived, kube packages, and admin CLIs (kubectl, helm, k9s, krew).

license:
  - MIT

tags:
  - ansible
  - linux
  - kubernetes
  - containerd
  - haproxy
  - keepalived
  - sysctl
  - proxy
  - krew
  - k9s
  - helm
  - debian
  - ubuntu

dependencies: {}

repository: https://github.com/rridane/ansible-base-systems
documentation: https://github.com/rridane/ansible-base-systems
homepage: https://github.com/rridane/ansible-base-systems
issues: https://github.com/rridane/ansible-base-systems

build_ignore:
  # VCS / CI / tooling
  - .git/
  - .github/
  - .gitignore
  - .editorconfig
  - .pre-commit-config.yaml
  - .venv/
  - venv/
  - .tox/
  - .mypy_cache/
  - __pycache__/
  - .pytest_cache/
  - .idea/
  - .vscode/

  # Artefacts et caches
  - "dist/"
  - "*.tar.gz"
  - "*.zip"
  - "*.log"
  - "*.retry"
  - ".venv"

  # Tests Molecule (souvent volumineux, inutiles côté Galaxy)
  - roles/*/molecule/

  # Ne PAS exclure les README de rôles !
  # Binaires/tarballs éventuels dans files/ (garde la config/templates)
  - roles/*/files/*.tar
  - roles/*/files/*.tar.gz
  - roles/*/files/*.tgz
  - roles/*/files/*.zip
  - roles/*/files/*.deb
  - roles/*/files/*.rpm

  # Docs/assets lourds
  - docs/
  - assets/
  - images/
  - screenshots/
