---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu-20
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ubuntu-22
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: debian-12
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ubuntu-22-version-32
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  inventory:
    group_vars:
      all:
        containerd_state: present
        containerd_root: /mnt/data/containerd
        containerd_registries:
          - host: "10.212.22.8"
            port: 5600
            insecure: true
            endpoints: ["http://10.212.22.8:5600"]
          - host: "10.212.22.8"
            port: 5500
            insecure: true
            endpoints: ["http://10.212.22.8:5500"]
    host_vars:
      ubuntu-22-version-32:
        containerd_version: 1.7.26-1
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."

verifier:
  name: testinfra
  options:
    verbose: true