---
# 1) Récupérer la dernière version si aucune n’est fournie
- name: "Kubent | Get latest release (curl) if version not specified"
  ansible.builtin.command: >
    curl -sL --fail --show-error
    -H "Accept: application/vnd.github+json"
    -H "User-Agent: ansible-curl"
    https://api.github.com/repos/doitintl/kube-no-trouble/releases/latest
  register: kubent_latest_raw
  changed_when: false
  when: (tools.kubent.version | default('') | string | length) == 0

# 2) Calculer la version effective
- name: "Kubent | Compute effective version"
  ansible.builtin.set_fact:
    kubent_version: >-
      {{
        tools.kubent.version
        if (tools.kubent.version | default('') | string | length) > 0
        else (kubent_latest_raw.stdout | from_json).tag_name
      }}

# 3) Télécharger le tarball
- name: "Kubent | Download tarball"
  ansible.builtin.command: >
    curl -L --fail --show-error
    -o /tmp/kubent.tar.gz
    "https://github.com/doitintl/kube-no-trouble/releases/download/{{ kubent_version }}/kubent-{{ kubent_version }}-linux-{{ tools.kubent.arch | default(system_arch) }}.tar.gz"
  args:
    creates: /tmp/kubent.tar.gz
  become: true

# 4) Installer
- name: "Kubent | Extract to {{ bin_path }}"
  ansible.builtin.unarchive:
    src: "/tmp/kubent.tar.gz"
    dest: "{{ bin_path }}"
    remote_src: true
  become: true
