---
- name: Get yq latest version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/mikefarah/yq/releases/latest"
    return_content: yes
  register: yq_latest
  when: tools.yq.version == ""

- name: Set yq version
  ansible.builtin.set_fact:
    yq_version: "{{ yq_latest.json.tag_name }}"
  when: tools.yq.version == ""

- name: Use specified yq version
  ansible.builtin.set_fact:
    yq_version: "{{ tools.yq.version }}"
  when: tools.yq.version != ""

- name: Download yq
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_{{ tools.yq.arch }}"
    dest: "{{ bin_path }}/yq"
    mode: "0755"
  become: true
