---
- name: Ensure krew base dir exists
  ansible.builtin.file:
    path: "{{ tools.krew.krew_root }}"
    state: directory
    mode: "0755"
  become: true

- name: Get krew latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/kubernetes-sigs/krew/releases/latest
    return_content: yes
  register: krew_latest
  when: tools.krew.version | default('') | string | length == 0

- name: Set krew version (auto)
  ansible.builtin.set_fact:
    krew_version: "{{ krew_latest.json.tag_name }}"
  when: tools.krew.version | default('') | string | length == 0

- name: Set krew version (pinned)
  ansible.builtin.set_fact:
    krew_version: "{{ tools.krew.version }}"
  when: tools.krew.version | default('') | string | length > 0

- name: Download krew tarball
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/krew/releases/download/{{ krew_version }}/krew-linux_{{ tools.krew.arch | default(system_arch) }}.tar.gz"
    dest: "/tmp/krew-linux_{{ tools.krew.arch | default(system_arch) }}.tar.gz"
    mode: "0644"
  become: true

- name: Unarchive krew tarball into krew_root
  ansible.builtin.unarchive:
    src: "/tmp/krew-linux_{{ tools.krew.arch | default(system_arch) }}.tar.gz"
    dest: "{{ tools.krew.krew_root }}"
    remote_src: true
    extra_opts: ["--strip-components=1"]
  become: true

# ⬇️ Étape bootstrap : crée {{ krew_root }}/bin/kubectl-krew
- name: Bootstrap krew (first install)
  ansible.builtin.shell: |
    set -e
    KREW_ROOT="{{ tools.krew.krew_root }}" \
    "{{ tools.krew.krew_root }}/krew-linux_{{ tools.krew.arch | default(system_arch) }}" install krew
  args:
    creates: "{{ tools.krew.krew_root }}/bin/kubectl-krew"
  become: true
  environment:
    # kubectl-krew n’a pas besoin d’un PATH spécial ici, mais si tu veux :
    PATH: "{{ ansible_env.PATH }}"

# Option propre pour le PATH système (évite /etc/environment)
- name: Ensure krew is on PATH for interactive shells
  ansible.builtin.copy:
    dest: /etc/profile.d/krew.sh
    mode: "0644"
    content: |
      # Added by system-k8s-cli-swissknife
      if [ -d "{{ tools.krew.krew_root }}/bin" ]; then
        case ":$PATH:" in
          *:"{{ tools.krew.krew_root }}/bin":*) ;;
          *) PATH="{{ tools.krew.krew_root }}/bin:$PATH" ;;
        esac
      fi
  become: true

# Liste les plugins déjà installés pour idempotence
- name: List installed krew plugins
  ansible.builtin.command: "{{ tools.krew.krew_root }}/bin/kubectl-krew list"
  register: krew_list
  changed_when: false
  failed_when: false
  environment:
    KREW_ROOT: "{{ tools.krew.krew_root }}"
    PATH: "{{ tools.krew.krew_root }}/bin:{{ ansible_env.PATH }}"
  become: true

- name: Install krew plugins
  ansible.builtin.command: "{{ tools.krew.krew_root }}/bin/kubectl-krew install {{ item }}"
  loop: "{{ tools.krew.plugins }}"
  when: krew_list.stdout is not defined or (item not in (krew_list.stdout_lines | default([])))
  environment:
    KREW_ROOT: "{{ tools.krew.krew_root }}"
    PATH: "{{ tools.krew.krew_root }}/bin:{{ ansible_env.PATH }}"
  become: true
