argument_specs:
  main:
    short_description: "Install k9s tool"
    description:
      - "Installe K9s depuis les releases GitHub."
      - "Par défaut, installe la dernière version stable."
    options:
      k9s_version:
        type: str
        required: false
        default: ""
        description:
          - "Version spécifique de K9s à installer (ex: '0.32.4')."
          - "Si vide, la dernière version sera automatiquement utilisée."
      k9s_arch:
        type: str
        required: false
        default: "amd64"
        choices: ["amd64", "arm64"]
        description:
          - "Architecture de la machine cible."
          - "Correspond au suffixe des binaires K9s sur GitHub."
      k9s_bin_path:
        type: str
        required: false
        default: "/usr/local/bin"
        description:
          - "Chemin de destination du binaire K9s."
          - "Doit être présent dans le PATH pour être exécuté."
