argument_specs:
  main:
    short_description: "Installer/désinstaller un bundle d'outils CLI Kubernetes (hors kubectl)"
    description:
      - "Gère krew (binaire + PATH, plugins si kubectl déjà présent) et divers outils (k9s, kustomize, helm, jq, yq, kubent, popeye)."
      - "Ne gère PAS kubectl."
    options:
      tools_state:
        type: str
        choices: [present, absent]
        default: present
      bin_path:
        type: str
        default: "/usr/local/bin"
      system_arch:
        type: str
        default: "amd64"
      tools:
        type: dict
        default: {}
      krew_profile_script_dir:
        type: str
        default: "/etc/profile.d"
      krew_profile_script_name:
        type: str
        default: "krew.sh"
