---
galaxy_info:
  role_name: system_proxy
  author: Rida Ridane
  description: >
    Configure les proxys système (APT, /etc/environment, systemd DefaultEnvironment) avec état présent/absent.
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - proxy
    - http
    - https
    - systemd
    - apt
    - linux
    - environment

dependencies: []
