- name: Converge
  hosts: all
  vars:
    unit_name: "test-service.service"
    unit_content: |
      [Unit]
      Description=Test Service
      After=network.target

      [Service]
      Type=oneshot
      ExecStart=/bin/echo "Test completed"
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    unit_dropins:
      - name: "override.conf"
        content: |
          [Service]
          Environment=TEST_VAR=test_value
    unit_envfile_path: "/etc/default/test-service"
    unit_envfile_content: |
      DEBUG=true
    unit_state: "started"
    unit_enabled: true
    unit_masked: false
    unit_present: true
    unit_scope: "system"
    unit_restart_on_change: false  # Désactivé pour éviter les problèmes
    unit_validate_with_systemd_analyze: false
  roles:
    - role: system_manage_systemd_unit