---
argument_specs:
  main:
    short_description: Clean a Kubernetes node (reset + CNI/Calico cleanup)
    description:
      - Run kubeadm reset and remove Kubernetes artifacts from a node.
      - Optionally purge packages and cleanup CNI/Calico state.
      - Includes an explicit confirmation step to prevent accidents.
    options:
      kube_cleanup_enabled:
        type: bool
        default: true
        description: Enable/disable the cleanup role execution.
      kube_cri_socket:
        type: str
        default: "/var/run/containerd/containerd.sock"
        description: CRI socket path passed to kubeadm reset.
      kube_ask_confirmation:
        type: bool
        default: true
        description: Ask interactively for confirmation before destructive actions.
      kube_cleanup_ack:
        type: str
        default: ""
        description: Pre-filled confirmation string (non-interactive environments).
      kube_cleanup_ack_expected:
        type: str
        default: "yes"
        description: Expected confirmation token (case-insensitive).
      kube_cleanup_packages:
        type: bool
        default: true
        description: Remove kubeadm/kubelet/kubectl packages (APT).
      kube_cleanup_cni:
        type: bool
        default: true
        description: Remove CNI configs and interfaces.
      kube_cleanup_calico:
        type: bool
        default: true
        description: Perform Calico-specific cleanup (files, bins, state, iptables).
