---
tools_state: present   # present | absent
tools:
  krew:
    enabled: true
    version: ""
    krew_root: "/opt/krew"
    plugins:
      - ctx
      - ns
      - neat
      - view-secret
      - who-can
      - rbac-view
      - tree
      - node-shell
      - stern
      - oidc-login

  k9s:
    enabled: true
    version: ""
    arch: "amd64"

  kustomize:
    enabled: true
    version: ""
    arch: "amd64"

  helm:
    enabled: true
    version: ""
    arch: "amd64"

  jq:
    enabled: true
    version: ""

  yq:
    enabled: true
    version: ""
    arch: "amd64"

  kubent:
    enabled: true
    version: ""
    arch: "amd64"

  popeye:
    enabled: true
    version: ""
    arch: "amd64"

bin_path: "/usr/local/bin"
system_arch: "amd64"

# ABSENT (when tools_state == "absent")
tools_to_remove:
  - helm
  - k9s
  - kustomize
  - kubent
  - popeye
  - yq

# Où l’on pose le script d’export PATH de krew
krew_profile_script_dir: "/etc/profile.d"
krew_profile_script_name: "krew.sh"
krew_profile_script_path: "{{ krew_profile_script_dir }}/{{ krew_profile_script_name }}"
