---
argument_specs:
  main:
    short_description: "Manage a systemd unit with optional drop-ins and envfile."
    options:
      unit_state:
        type: str
        choices: [started, stopped, restarted, reloaded, null]
        default: started
      unit_enabled:
        type: bool
        default: true
      unit_masked:
        type: bool
        default: false
      unit_present:
        type: bool
        default: true
      unit_scope:
        type: str
        choices: [system, user]
        default: system
      unit_name:
        type: str
        required: true

      unit_content:
        type: str
        default: ""
      unit_template_src:
        type: str
        default: ""
      unit_src_path:
        type: str
        default: ""

      unit_dropins:
        type: list
        elements: dict
        default: []
      unit_envfile_path:
        type: str
        default: ""
      unit_envfile_content:
        type: str
        default: ""

      unit_restart_on_change:
        type: bool
        default: true
      unit_validate_with_systemd_analyze:
        type: bool
        default: true
