---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: lb1
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - haproxy-ha

  - name: lb2
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - haproxy-ha

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    group_vars:
      haproxy-ha:
        containerd_state: present   # ← pas utilisé mais homogénéité
        # ==== Variables HAProxy ====
        haproxy_username: haproxy
        haproxy_groupname: haproxy
        haproxy_default_mode: tcp

        haproxy_frontend_stats_port: 8404
        haproxy_frontend_stats_username: admin
        haproxy_frontend_stats_password: admin
        haproxy_dataplaneapi_user: dataplane

        masters:
          - hostname: master1
            ip: 10.10.0.11
            port: 6443
          - hostname: master2
            ip: 10.10.0.12
            port: 6443

        nodes:
          - hostname: node1
            ip: 10.10.0.21
            port: 9000
          - hostname: node2
            ip: 10.10.0.22
            port: 9000

        api_server_frontend_port: 6443
        traefik_frontend_port: 9000

        keepalived_interface: veth0
        ha_vip: 10.10.0.200

    host_vars:
      lb1:
        keepalived_role: MASTER
      lb2:
        keepalived_role: BACKUP

verifier:
  name: testinfra
  options:
    verbose: true
