- name: Get kustomize latest version
  uri:
    url: "https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest"
    return_content: yes
  register: kustomize_latest
  when: tools.kustomize.version == ""

- name: Set kustomize version
  set_fact:
    kustomize_version: "{{ kustomize_latest.json.tag_name | regex_replace('^kustomize/', '') }}"
  when: tools.kustomize.version == ""

- name: Use specified kustomize version
  set_fact:
    kustomize_version: "{{ tools.kustomize.version }}"
  when: tools.kustomize.version != ""

- name: Download kustomize
  get_url:
    url: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_{{ tools.kustomize.arch }}.tar.gz"
    dest: "/tmp/kustomize.tar.gz"
  become: true

- name: Install kustomize
  unarchive:
    src: "/tmp/kustomize.tar.gz"
    dest: "{{ bin_path }}"
    remote_src: yes
  become: true