---
- name: Prepare hosts
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Install tar, gzip, curl, ca-certificates
      package:
        name:
          - tar
          - gzip
          - curl
          - ca-certificates
        state: present

    - name: Ensure /usr/local/bin exists
      ansible.builtin.file:
        path: /usr/local/bin
        state: directory
        mode: "0755"
