dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: systemd-unit-test
    image: docker.io/jrei/systemd-ubuntu:22.04
    privileged: true
    command: /sbin/init
    tmpfs:
      /tmp: "rw,nosuid,nodev,noexec,mode=1777"
      /run: "rw,nosuid,nodev,mode=0755"
      /run/lock: "rw,nosuid,nodev,mode=0755"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
verifier:
  name: testinfra
  directory: tests