---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  # Distribution test machines
  - name: ubuntu-20
    image: "docker.io/geerlingguy/docker-ubuntu2004-ansible"
    pre_build_image: true
  - name: ubuntu-22
    image: "docker.io/geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
  - name: debian-12
    image: "docker.io/geerlingguy/docker-debian12-ansible:latest"
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        kube_cleanup_enabled: true
        kube_ask_confirmation: false
        kube_cleanup_ack: "yes"
        kube_cleanup_packages: true
        kube_cleanup_cni: true
        kube_cleanup_calico: true
    host_vars:
      ubuntu-22:
        kube_state: present
      ubuntu-20:
        kube_state: absent
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."

verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true

scenario:
  name: default

