---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Ensure basic TLS utils
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true
