---
- name: "HA pair | Install packages"
  become: true
  block:
    - name: "Install HAProxy & Keepalived"
      ansible.builtin.apt:
        name:
          - haproxy
          - keepalived
        state: present
        update_cache: true

    - name: "Enable services at boot"
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
      loop:
        - haproxy
        - keepalived

- name: "HAProxy | Configure"
  become: true
  block:
    - name: "Render haproxy.cfg"
      ansible.builtin.template:
        src: templates/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0644"
      notify: "haproxy | validate & restart"

- name: "Keepalived | Configure"
  become: true
  block:
    - name: "Render keepalived (lb1)"
      ansible.builtin.template:
        src: templates/keepalived_1.cfg
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      when: inventory_hostname == "lb1"
      notify: "keepalived | validate & restart"

    - name: "Render keepalived (lb2)"
      ansible.builtin.template:
        src: templates/keepalived_2.cfg
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      when: inventory_hostname == "lb2"
      notify: "keepalived | validate & restart"
