---
- name: Compute effective proxy values
  ansible.builtin.set_fact:
    _http_proxy: "{{ http_proxy }}"
    _https_proxy: "{{ (https_proxy | default('')) | ternary(https_proxy, http_proxy) }}"
    _no_proxy: >-
      {{ (no_proxy | default('')) | ternary(
           no_proxy,
           ((no_proxy_list + (no_proxy_extra | default([]))) | unique) | join(',')
         ) }}
  become: true

# 1) APT
- name: Ensure APT proxy (present)
  ansible.builtin.template:
    src: apt_proxy.conf.j2
    dest: "{{ apt_proxy_file }}"
    mode: "0644"
  when: proxy_state == 'present'
  become: true

- name: Ensure APT proxy (absent)
  ansible.builtin.file:
    path: "{{ apt_proxy_file }}"
    state: absent
  when: proxy_state == 'absent'
  become: true

# 2) /etc/environment via bloc
- name: Ensure /etc/environment proxy block (present)
  ansible.builtin.blockinfile:
    path: "{{ environment_file }}"
    marker: "# ANSIBLE-MANAGED {{ environment_block_name }} {mark}"
    create: true
    mode: "0644"
    block: "{{ lookup('template', 'environment_proxy_block.j2') }}"
  when: proxy_state == 'present'
  become: true

- name: Ensure /etc/environment proxy block (absent)
  ansible.builtin.blockinfile:
    path: "{{ environment_file }}"
    marker: "# ANSIBLE-MANAGED {{ environment_block_name }} {mark}"
    state: absent
  when: proxy_state == 'absent'
  become: true

# 3) systemd DefaultEnvironment (persistant)
- name: Ensure systemd drop-in dir exists
  ansible.builtin.file:
    path: "{{ systemd_dropin_dir }}"
    state: directory
    mode: "0755"
  when: proxy_state == 'present'
  become: true

- name: Persist proxies in systemd DefaultEnvironment (present)
  ansible.builtin.template:
    src: systemd_default_env.conf.j2
    dest: "{{ systemd_dropin_dir }}/{{ systemd_dropin_file }}"
    mode: "0644"
  when: proxy_state == 'present'
  notify: [systemd daemon reexec]
  become: true

- name: Remove systemd DefaultEnvironment drop-in (absent)
  ansible.builtin.file:
    path: "{{ systemd_dropin_dir }}/{{ systemd_dropin_file }}"
    state: absent
  when: proxy_state == 'absent'
  notify: [systemd daemon reexec]
  become: true
