# handlers/main.yml
---
# HAProxy
- name: "haproxy | validate config"
  listen: "haproxy | validate & restart"
  become: true
  ansible.builtin.command: haproxy -c -f /etc/haproxy/haproxy.cfg
  changed_when: false

- name: "haproxy | restart"
  listen: "haproxy | validate & restart"
  become: true
  ansible.builtin.systemd:
    name: haproxy
    state: restarted

# Keepalived
- name: "keepalived | validate config"
  listen: "keepalived | validate & restart"
  become: true
  ansible.builtin.command: keepalived -t -f /etc/keepalived/keepalived.conf
  changed_when: false

- name: "keepalived | restart"
  listen: "keepalived | validate & restart"
  become: true
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
