---
galaxy_info:
  role_name: system_install_k9s
  author: Rida Ridane
  description: Installe K9s depuis les releases GitHub (dernière version par défaut ou version spécifiée).
  license: MIT

  namespace: rridane
  platforms:
    - name: Debian
      versions: [bookworm]
    - name: Ubuntu
      versions: [focal, jammy]

  galaxy_tags:
    - k9s
    - kubernetes
    - cli
    - ops
    - devops
    - tooling

dependencies: []
