---
argument_specs:
  main:
    short_description: "Charge/Décharge les modules noyau réseau et applique/retire les sysctl associés."
    options:
      net_tuning_state:
        type: str
        choices: [present, absent]
        default: present
        description:
          - "present => applique modules + sysctl"
          - "absent  => retire modules + sysctl et supprime les fichiers .conf"
      net_tuning_modules:
        type: list
        elements: str
        default:
          - overlay
          - br_netfilter
        description:
          - "Modules noyau à charger au boot et à chaud."
      net_tuning_sysctls:
        type: dict
        default:
          net.bridge.bridge-nf-call-ip6tables: 1
          net.bridge.bridge-nf-call-iptables: 1
          net.ipv4.ip_forward: 1
        description:
          - "Clés sysctl à appliquer (clé => valeur)."
      net_tuning_modules_conf_path:
        type: str
        default: "/etc/modules-load.d/net-tuning.conf"
        description:
          - "Chemin du fichier modules-load.d généré."
      net_tuning_sysctl_conf_path:
        type: str
        default: "/etc/sysctl.d/90-net-tuning.conf"
        description:
          - "Chemin du fichier sysctl.d généré."
