---
- name: Prepare hosts
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
