- name: Stop and disable cntlm service
  systemd:
    name: cntlm
    state: stopped
    enabled: no
  become: yes
  ignore_errors: yes

- name: Remove cntlm systemd service unit
  file:
    path: /etc/systemd/system/cntlm.service
    state: absent
  become: yes

- name: Remove cntlm systemd drop-in directory
  file:
    path: /etc/systemd/system/cntlm.service.d
    state: absent
  become: yes

- name: Remove cntlm configuration
  file:
    path: /etc/cntlm.conf
    state: absent
  become: yes

- name: Remove cntlm binary (default install location)
  file:
    path: /usr/local/bin/cntlm
    state: absent
  become: yes

- name: Reload systemd to apply unit removals
  systemd:
    daemon_reload: yes
  become: yes
